import type { Metadata } from "next";
import "./globals.css";
import { playfair } from "@/lib/fonts";
import { NextUIProviders } from "@/providers/NextUIprovider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import GhostVerticalText from "@/components/general/GhostVerticalText";
import { NextJSBlob, SaqGreenBlob } from "@/components/general/GlowingBlobs";
import { ModeToggle } from "@/components/general/ThemeToggle";
import { ScrollShadow } from "@nextui-org/react";
import { Toaster } from "@/components/ui/toaster";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Say a Qoute",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={clsx(
          playfair.className,
          "bg-light-gray-700  dark:bg-dark-gray-900 "
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <NextUIProviders>
            <ModeToggle />
            <GhostVerticalText />
            <NextJSBlob />
            <SaqGreenBlob />
            <>
              <Toaster />
              {props.children}
            </>
          </NextUIProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
